name: assessment-geospatial
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py310h458dff3_0
  - blosc=1.21.6=hfd34d9b_1
  - brotli-python=1.2.0=py310hfff998d_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - deprecated=1.3.1=pyhd8ed1ab_1
  - freexl=2.0.0=hf297d47_2
  - gdal=3.12.1=py310h2ed3b37_1
  - geos=3.14.1=hdade9fe_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - krb5=1.21.3=hdf4eb48_0
  - lerc=4.0.0=h6470a55_1
  - libarchive=3.8.5=gpl_he24518a_100
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libcurl=8.18.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libgdal-core=3.12.1=h4c6072a_1
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.1=hf3f85d1_8
  - libkml=1.3.0=h68a222c_1022
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libpng=1.6.54=h7351971_0
  - librttopo=1.1.0=haa95264_20
  - libspatialite=5.1.0=gpl_h0cd62ae_119
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h8f73337_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxml2-devel=2.15.1=h779ef1b_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - minizip=4.0.10=h9fa1bad_0
  - mkl=2025.3.0=hac47afa_455
  - muparser=2.3.5=he0c23c2_0
  - numpy=2.2.6=py310h4987827_0
  - openeo=0.46.0=pyhd8ed1ab_0
  - openssl=3.6.1=hf411b9b_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.3=py310hed136d8_2
  - pcre2=10.47=hd2b5f0e_0
  - pip=26.0.1=pyh8b19718_0
  - proj=9.7.1=hd30e2cd_2
  - pyparsing=3.3.2=pyhcf101f3_0
  - pysocks=1.7.1=pyh09c184e_7
  - pystac=1.14.3=pyhd8ed1ab_0
  - python=3.10.19=hc20f281_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - rasterio=1.4.4=py310h2807112_2
  - requests=2.32.5=pyhcf101f3_1
  - setuptools=80.10.2=pyh332efcf_0
  - shapely=2.1.2=py310h62de375_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sqlite=3.51.2=hdb435a2_0
  - tbb=2022.3.0=h3155e25_2
  - tk=8.6.13=h6ed50ae_3
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - wheel=0.46.3=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=2.1.1=py310h29418f3_0
  - xarray=2025.1.1=pyhd8ed1ab_0
  - xerces-c=3.3.0=hac47afa_1
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.7=h534d264_6
prefix: C:\Users\HP-122024\anaconda3\envs\assessment-geospatial
